server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epos_master
    username: epos
    password: epos
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration/master

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.flywaydb: info

epos:
  jwt:
    secret: "CHANGE_ME_TO_32+_CHARS_SECRET_CHANGE_ME_123456"
